[logging]
; enabled=true
; hotkey_toggle=VK_CONTROL+O
; hotkey_frame=VK_CONTROL+P

[graphics]
enhanced=true
interp=true
;linear=true
                               _
slang_shader_gba=slang-shaders/custom/ScaleFx+LCD.slangp
                               ^

[Favorites]
custom/ScaleFx+LCD.slangp
custom/psp-freescale.slangp
custom/Xbrz-Free+LCD3x.slangp

[Smoothing]
scalefx/scalefx.slangp
xbrz/xbrz-freescale-multipass.slangp
presets/scalefx9-aa-blur-hazy-vibrance.slangp

[CRT]
crt/crt-royale.slangp
crt/crt-lottes.slangp
crt/crt-consumer.slangp

[LCD]
handheld/lcd3x.slangp
handheld/lcd1x_psp.slangp
handheld/lcd-shader.slangp

[VHS]
vhs/VHSPro.slangp
vhs/ntsc-vcr.slangp
vhs/vhs_and_crt_godot.slangp


/////////////////////////////////////////////////
;bezel/Mega_Bezel/Presets/MBZ__0__SMOOTH-ADV.slangp
;custom/Stock.slangp
;test/format.slangp
