;================================================
[graphics]
enhanced=true
linear=false
interp=true
                             _
slang_shader_1=slang-shaders/scalefx/scalefx.slangp
                             ^
slang_shader_2=slang-shaders/custom/ScaleFx+LCD.slangp
                             ^
slang_shader_3=slang-shaders/crt/crt-lottes.slangp
                             ^
[Favorites]
custom/ScaleFx+LCD.slangp
custom/psp-freescale.slangp
custom/Xbrz-Free+LCD3x.slangp

[Smoothing]
scalefx/scalefx.slangp
xbrz/xbrz-freescale-multipass.slangp
presets/scalefx9-aa-blur-hazy-vibrance.slangp

[CRT]
crt/crt-royale.slangp
crt/crt-lottes.slangp
crt/crt-consumer.slangp

[LCD]
handheld/lcd3x.slangp
handheld/lcd1x_psp.slangp
handheld/lcd-shader.slangp

[VHS]
vhs/VHSPro.slangp
vhs/ntsc-vcr.slangp
vhs/vhs_and_crt_godot.slangp

;================================================

[Keybinds]
hotkey_shader_toggle=VK_OEM_3
hotkey_increase_text_aura=VK_OEM_MINUS
hotkey_decrease_text_aura=VK_OEM_PLUS
hotkey_increase_sharpness=VK_OEM_6
hotkey_decrease_sharpness=VK_OEM_4
hotkey_shader_prev=1
hotkey_shader_next=2
hotkey_widescreen=3

[Controller]
hotkey_shader_toggle_pad=XINPUT_LS
;hotkey_increase_text_aura_pad=XINPUT_B
;hotkey_decrease_text_aura_pad=XINPUT_Y
;hotkey_widescreen_pad=XINPUT_RT
;hotkey_shader_prev_pad=XINPUT_LT
hotkey_shader_next_pad=XINPUT_RS

[Defaults]
shader_toggle=TRUE
key_threshold=0.07
key_sharpness=4.0
widescreen=FALSE

;================================================

[logging]  
; enabled=true
; hotkey_toggle=VK_CONTROL+O
; hotkey_frame=VK_CONTROL+P
;custom/Stock.slangp
;test/format.slangp
;================================================